on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Page 
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment 
concurrency:
  group: "test"
  cancel-in-progress: true
  
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
    - name: Checkout
      uses: actions/checkout@v3
    - run: npm install
    - run: npm run test
